"""add new columns for user

Revision ID: 31400a29cc69
Revises: 1a7f96d207d1
Create Date: 2022-04-30 16:55:18.282298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31400a29cc69'
down_revision = '1a7f96d207d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_time')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
